export enum actionType {
  SET_OFFSET = "SET_OFFSET",
  STORE_REQUEST = "STORE_REQUEST",

  FETCH_BOOKS_START = "FETCH_BOOKS_START",
  FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS",
  FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE",
  CLEAR_BOOKS = "CLEAR_BOOKS",

  BOOKS_NOT_FOUND = "BOOKS_NOT_FOUND",
  SELECT_BOOK = "SELECT_BOOK",
}
