export const SET_OFFSET = "SET_OFFSET"
export const STORE_REQUEST = "STORE_REQUEST"

export const FETCH_BOOKS_START = "FETCH_BOOKS_START"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"
export const CLEAR_BOOKS = "CLEAR_BOOKS"

export const BOOKS_NOT_FOUND = "BOOKS_NOT_FOUND"
export const SELECT_BOOK = "SELECT_BOOK"
